######################################################
#   Triggers
######################################################
trigger:
  batch: true
  branches:
    include:
      - master
  
  paths:
    include:
    - ApiE2ETestsWithDocker/*
pr:
  branches:
    include:
      - master
  
  paths:
    include:
    - ApiE2ETestsWithDocker/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
