jobs:
  ####################################################
  #   JOB 3: Publish Pre-release NuGet
  ####################################################
  - job: Publish_Prerelease_NuGet
    dependsOn: Test
    pool:
      vmImage: 'ubuntu-16.04'

    steps:
      ################################################
      # Step 0: No checkout as we're getting
      #         built code from artifacts
      ################################################
      - checkout: none

      ################################################
      # Step 1: Get built source code
      #         from build artifacts
      ################################################
      - task: DownloadBuildArtifacts@0
        displayName: 'Download Built Source Code'
        inputs:
          artifactName: BuiltSourceCode
          downloadPath: $(Build.SourcesDirectory)

      ################################################
      # Step 2: Create alpha NuGet package
      ################################################
      - task: DotNetCoreCLI@2
        displayName: Pack
        inputs:
          command: pack
          projects: '$(Build.SourcesDirectory)/BuiltSourceCode/$(solution_path)'
          arguments: '--configuration $(config)'
          packDestination: '$(Build.ArtifactStagingDirectory)'
          versioningScheme: 'byEnvVar'
          versionEnvVar: 'AlphaNugetVersion'

      ################################################
      # Step 3: Publish alpha NuGet package
      ################################################
      - task: NuGetCommand@2
        displayName: Publish packages to NuGet
        inputs:
          command: 'push'
          nuGetFeedType: 'external'
          packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
          publishFeedCredentials: 'NuGet'

      ################################################
      # Step 3: Publish alpha symbols NuGet package
      ################################################
      - task: NuGetCommand@2
        displayName: Publish symbol packages to NuGet
        inputs:
          command: 'push'
          nuGetFeedType: 'external'
          packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.snupkg'
          publishFeedCredentials: 'NuGet'
